//------------------------------------------------------------------------
// Copyright(c) 2024 Vargason.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Strainer.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Strainer VST3 (64Bit)"
#else
#define stringFileDescription	"Strainer VST3"
#endif
#define stringCompanyName		"Vargason\0"
#define stringLegalCopyright	"Copyright(c) 2024 Vargason."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
